#!/bin/sh

# Function to validate a URL
is_valid_url() {
  url="$1"
  # Check if URL is in a valid format
  if echo "$url" | grep -E -q '^https?://[a-zA-Z0-9.-]+(:[0-9]+)?(/.*)?$'; then
    # Check if URL is reachable by making a simple HEAD request
    curl --head --silent --fail "$url" > /dev/null 2>&1
    return $?
  else
    return 1
  fi
}

# Function to send a webhook call
send_webhook() {
  url="$1"
  status="$2"
  extra_args="$3"

  if is_valid_url "$url"; then
    echo "Executing webhook call to ${url} with status ${status}"
    curl --request POST \
      --url "$url" \
      --header 'Content-Type: application/json' \
      --data "{\"status\": \"${status}\"}" \
      --max-time 10 \
      --retry 5 \
      $extra_args
  else
    echo "Invalid URL: ${url}"
  fi
}

# Action passed as an argument
ACTION="$1"

case "$ACTION" in
  "error")
    send_webhook "$WEBHOOK_URL" "error" "$WEBHOOK_EXTRA_ARGS"
    send_webhook "$WEBHOOK_ERROR_URL" "error" "$WEBHOOK_EXTRA_ARGS"
  ;;

  "pre-backup")
    send_webhook "$WEBHOOK_PRE_BACKUP_URL" "pre-backup" "$WEBHOOK_EXTRA_ARGS"
  ;;

  "post-backup")
    send_webhook "$WEBHOOK_URL" "post-backup" "$WEBHOOK_EXTRA_ARGS"
    send_webhook "$WEBHOOK_POST_BACKUP_URL" "post-backup" "$WEBHOOK_EXTRA_ARGS"
  ;;
esac
