name: Docker Push Readme

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed  # Only trigger after the first workflow completes

jobs:
  push-readme:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if CI succeeded
    runs-on: ubuntu-22.04
    environment: docker.io
    steps:
      - uses: actions/checkout@v4

      - name: Generate README for DockerHub
        run: cp dockerhub-header.md dockerhub.md && awk '{if(p)print}/^# /{p=1}' README.md >> dockerhub.md

      - name: Push README to DockerHub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/postgres-backup-telegram
          provider: dockerhub
          short_description: 'Backup PostgreSQL to the local filesystem with periodic backups, automatic rotation, and Telegram bot integration to send the latest backup file.'
          readme_file: 'dockerhub.md'
